name: Run Tests
on: [push, pull_request]
jobs:
  gradle:
    strategy:
      matrix:
        gradle: [4.9, 4.10.2, 6.7.1]
        java: [8-jdk, 11-jdk, 15-jdk]
        exclude:
          - java: jdk15
            gradle: 4.9
          - java: jdk15
            gradle: 4.10.2
          - java: jdk11
            gradle: 4.9
          - java: jdk11
            gradle: 4.10.2
    runs-on: ubuntu-20.04
    container:
      image: gradle:${{ matrix.gradle }}-${{ matrix.java }}
      options: --user root
    steps:
      - uses: actions/checkout@v2
      - run: gradle build publishToMavenLocal --parallel --stacktrace
      - uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/
